name: Deploy to ECS

on:
  push:
    branches:
      - main
env:
BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      #with:
        #terraform_version: 1.0.0
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change to your desired AWS region
    
    - name: Terraform Init
      run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
      
    - name: Terraform plan
      run: terraform plan -no-color -input=false -out planfile
      continue-on-error: true
    
    - name: Terraform Apply
      id: apple
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false -parallelism=1 planfile

